name: xmonad-rszczers
version: 0.0.1
synopsis: XMonad Setting
github: rszczers/.xmonad
author: rszczers
maintainer: rafal@szczerski.pl
dependencies:
  - X11
  - base
  - xmonad
  - xmonad-contrib
executables:
  xmonad:
    main: xmonad.hs
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -threaded
      - -O2
      - -with-rtsopts=-N4
